### ISSUE TITLE
TODO list: final project delivery

### ISSUE THREAD

**Issue by samuelmasuy** [samuelmasuy/psychic-umbrella#5]
## Character generation / Edition

_Creating/editing a fighter character following the d20 game rules as described below:_ 
- [x] level
- [x] ability scores
- [x]  ability modifiers
- [x] hit points and base attack modifier proportional to level.
- [ ] Inventory pane, including worn items: armor, shield, gloves, bracers, rings, helmet, boots,
belt, backpack. Equip /unequip items. Wearing a maximum one of each kind of item.
- [x]  Save/load a character to/from a file, including all owned/worn items.

## Map generation / Edition

- [x] Create a map of a user-defined size

_Place game elements on a map:_
- [x] entry point
- [x] exit point
- [x] doors
- [x] chests
- [x] monsters
- [ ] ...

- [x] Save/load a map to/from a file

## Play 

- [x] Select a map  from a list of saved ones
- [ ] Select a character from a list of saved ones

_Start the game by having:_
- [x] the player character placed on the starting point
- [ ] the monsters' levels are adjusted to the level of the player character
- [ ] a chest containing items that the character can acquire and use, and that are adapted to his **level is on the map**

- [x] Player character can equip/unequip items during play
- [ ] Magic items have effects on characteristics or armor class (see below). Armor class
adjusted to worn armor and shield, ability scores adjusted to worn items magical modifiers

_The game follows the turn-based game sequence as described below, including moving
and attack following the d20 rules_
- [ ] End the map by having the character stepping on the exit point, the exit point being activated only when all **monsters on the map have been defeated**
- [ ] Player character automatically goes up a level and is saved upon exiting the map. The
player is then given the option to play another map with the same character or exit the
game
- [ ] Logging window clearly showing that the d20 rules are followed during game play, including
dice rolls, and all applicable values and modifiers used in the calculations

## Design and programming style

- [ ] Use of significant names for identifiers ⚠️ 
- [ ] code readability
- [ ] comments (doxygen style), it must produce valid documents  ⚠️ 
- [ ] modular design ⚠️

_Use of observer pattern for:_
- [x] character
- [x] map
- [ ] item containers (backpack/worn items,chest)

_Use of builder pattern for:_
- [x] character
- [x] map
- [x] chest
